baseURL = 'https://jota-ele-ene.github.io/myhs/'
languageCode = 'en-us'
title = 'José Luis Núñez'
theme = 'just-me'

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]


[params]
  author = "José Luis Núñez"
  author_link = "https://jota-ele-ene.github.io/myhs/"
  ga_tracking_id = "UA-52910819-1"
  unsplash_url = "https://competent-edison-8543fa.netlify.app/.netlify/functions/api"
  #unsplash_url = "https://rnd-images.000webhostapp.com/"
